export const problemsDeg = [
  { id: 'p1', question: 'sin 0°', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p2', question: 'sin 30°', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p3', question: 'sin 45°', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p4', question: 'sin 60°', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p5', question: 'sin 90°', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p6', question: 'sin 120°', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p7', question: 'sin 135°', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p8', question: 'sin 150°', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p9', question: 'sin 180°', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p10', question: 'sin 210°', correctAnswerId: 'ans9' },
  { id: 'p11', question: 'sin 225°', correctAnswerId: 'ans10' },
  { id: 'p12', question: 'sin 240°', correctAnswerId: 'ans11' },
  { id: 'p13', question: 'sin 270°', correctAnswerId: 'ans14' },
  { id: 'p14', question: 'sin 300°', correctAnswerId: 'ans11' },
  { id: 'p15', question: 'sin 315°', correctAnswerId: 'ans10' },
  { id: 'p16', question: 'sin 330°', correctAnswerId: 'ans9' },
  { id: 'p17', question: 'sin 360°', correctAnswerId: 'ans1' },

  { id: 'p18', question: 'cos 0°', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p19', question: 'cos 30°', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p20', question: 'cos 45°', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p21', question: 'cos 60°', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p22', question: 'cos 90°', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p23', question: 'cos 120°', correctAnswerId: 'ans9', category: 'H1' },
  { id: 'p24', question: 'cos 135°', correctAnswerId: 'ans10', category: 'H1' },
  { id: 'p25', question: 'cos 150°', correctAnswerId: 'ans11', category: 'H1' },
  { id: 'p26', question: 'cos 180°', correctAnswerId: 'ans14', category: 'H1' },
  { id: 'p27', question: 'cos 210°', correctAnswerId: 'ans11' },
  { id: 'p28', question: 'cos 225°', correctAnswerId: 'ans10' },
  { id: 'p29', question: 'cos 240°', correctAnswerId: 'ans9' },
  { id: 'p30', question: 'cos 270°', correctAnswerId: 'ans1' },
  { id: 'p31', question: 'cos 300°', correctAnswerId: 'ans2' },
  { id: 'p32', question: 'cos 315°', correctAnswerId: 'ans3' },
  { id: 'p33', question: 'cos 330°', correctAnswerId: 'ans4' },
  { id: 'p34', question: 'cos 360°', correctAnswerId: 'ans7' },

  { id: 'p35', question: 'tan 0°', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p36', question: 'tan 30°', correctAnswerId: 'ans5', category: 'H1' },
  { id: 'p37', question: 'tan 45°', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p38', question: 'tan 60°', correctAnswerId: 'ans6', category: 'H1' },
  { id: 'p39', question: 'tan 90°', correctAnswerId: 'ans8', category: 'H1' },
  { id: 'p40', question: 'tan 120°', correctAnswerId: 'ans13', category: 'H1' },
  { id: 'p41', question: 'tan 135°', correctAnswerId: 'ans14', category: 'H1' },
  { id: 'p42', question: 'tan 150°', correctAnswerId: 'ans12', category: 'H1' },
  { id: 'p43', question: 'tan 180°', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p44', question: 'tan 210°', correctAnswerId: 'ans5' },
  { id: 'p45', question: 'tan 225°', correctAnswerId: 'ans7' },
  { id: 'p46', question: 'tan 240°', correctAnswerId: 'ans6' },
  { id: 'p47', question: 'tan 270°', correctAnswerId: 'ans8' },
  { id: 'p48', question: 'tan 300°', correctAnswerId: 'ans13' },
  { id: 'p49', question: 'tan 315°', correctAnswerId: 'ans14' },
  { id: 'p50', question: 'tan 330°', correctAnswerId: 'ans12' },
  { id: 'p51', question: 'tan 360°', correctAnswerId: 'ans1' },
];
