export const problemsRad = [
  { id: 'p1', question: '\\sin(-2\\pi)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p2', question: '\\sin(-\\frac{11\\pi}{6})', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p3', question: '\\sin(-\\frac{7\\pi}{4})', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p4', question: '\\sin(-\\frac{5\\pi}{3})', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p5', question: '\\sin(-\\frac{3\\pi}{2})', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p6', question: '\\sin(-\\frac{4\\pi}{3})', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p7', question: '\\sin(-\\frac{5\\pi}{4})', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p8', question: '\\sin(-\\frac{7\\pi}{6})', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p9', question: '\\sin(-\\pi)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p10', question: '\\sin(-\\frac{5\\pi}{6})', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p11', question: '\\sin(-\\frac{3\\pi}{4})', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p12', question: '\\sin(-\\frac{2\\pi}{3})', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p13', question: '\\sin(-\\frac{\\pi}{2})', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p14', question: '\\sin(-\\frac{\\pi}{3})', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p15', question: '\\sin(-\\frac{\\pi}{4})', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p16', question: '\\sin(-\\frac{\\pi}{6})', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p17', question: '\\sin 0', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p18', question: '\\sin \\frac{\\pi}{6}', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p19', question: '\\sin \\frac{\\pi}{4}', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p20', question: '\\sin \\frac{\\pi}{3}', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p21', question: '\\sin \\frac{\\pi}{2}', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p22', question: '\\sin \\frac{2\\pi}{3}', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p23', question: '\\sin \\frac{3\\pi}{4}', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p24', question: '\\sin \\frac{5\\pi}{6}', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p25', question: '\\sin \\pi', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p26', question: '\\sin \\frac{7\\pi}{6}', correctAnswerId: 'ans9', category: 'H2' },
  { id: 'p27', question: '\\sin \\frac{5\\pi}{4}', correctAnswerId: 'ans10', category: 'H2' },
  { id: 'p28', question: '\\sin \\frac{4\\pi}{3}', correctAnswerId: 'ans11', category: 'H2' },
  { id: 'p29', question: '\\sin \\frac{3\\pi}{2}', correctAnswerId: 'ans14', category: 'H2' },
  { id: 'p30', question: '\\sin \\frac{5\\pi}{3}', correctAnswerId: 'ans11', category: 'H2' },
  { id: 'p31', question: '\\sin \\frac{7\\pi}{4}', correctAnswerId: 'ans10', category: 'H2' },
  { id: 'p32', question: '\\sin \\frac{11\\pi}{6}', correctAnswerId: 'ans9', category: 'H2' },
  { id: 'p33', question: '\\sin 2\\pi', correctAnswerId: 'ans1', category: 'H2' },
  { id: 'p34', question: '\\sin \\frac{13\\pi}{6}', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p35', question: '\\sin \\frac{9\\pi}{4}', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p36', question: '\\sin \\frac{7\\pi}{3}', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p37', question: '\\sin \\frac{5\\pi}{2}', correctAnswerId: 'ans7', category: 'H3' },
  { id: 'p38', question: '\\sin \\frac{8\\pi}{3}', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p39', question: '\\sin \\frac{11\\pi}{3}', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p40', question: '\\sin \\frac{17\\pi}{6}', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p41', question: '\\sin 3\\pi', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p42', question: '\\sin \\frac{19\\pi}{6}', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p43', question: '\\sin \\frac{13\\pi}{4}', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p44', question: '\\sin \\frac{10\\pi}{3}', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p45', question: '\\sin \\frac{21\\pi}{6}', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p46', question: '\\sin \\frac{11\\pi}{3}', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p47', question: '\\sin \\frac{27\\pi}{12}', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p48', question: '\\sin \\frac{23\\pi}{12}', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p49', question: '\\sin 4\\pi', correctAnswerId: 'ans1', category: 'H3' },

  { id: 'p50', question: '\\cos(-2\\pi)', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p51', question: '\\cos(-\\frac{11\\pi}{6})', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p52', question: '\\cos(-\\frac{7\\pi}{4})', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p53', question: '\\cos(-\\frac{5\\pi}{3})', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p54', question: '\\cos(-\\frac{3\\pi}{2})', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p55', question: '\\cos(-\\frac{4\\pi}{3})', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p56', question: '\\cos(-\\frac{5\\pi}{4})', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p57', question: '\\cos(-\\frac{7\\pi}{6})', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p58', question: '\\cos(-\\pi)', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p59', question: '\\cos(-\\frac{5\\pi}{6})', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p60', question: '\\cos(-\\frac{3\\pi}{4})', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p61', question: '\\cos(-\\frac{2\\pi}{3})', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p62', question: '\\cos(-\\frac{\\pi}{2})', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p63', question: '\\cos(-\\frac{\\pi}{3})', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p64', question: '\\cos(-\\frac{\\pi}{4})', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p65', question: '\\cos(-\\frac{\\pi}{6})', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p66', question: '\\cos 0', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p67', question: '\\cos \\frac{\\pi}{6}', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p68', question: '\\cos \\frac{\\pi}{4}', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p69', question: '\\cos \\frac{\\pi}{3}', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p70', question: '\\cos \\frac{\\pi}{2}', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p71', question: '\\cos \\frac{2\\pi}{3}', correctAnswerId: 'ans9', category: 'H1' },
  { id: 'p72', question: '\\cos \\frac{3\\pi}{4}', correctAnswerId: 'ans10', category: 'H1' },
  { id: 'p73', question: '\\cos \\frac{5\\pi}{6}', correctAnswerId: 'ans11', category: 'H1' },
  { id: 'p74', question: '\\cos \\pi', correctAnswerId: 'ans14', category: 'H1' },
  { id: 'p75', question: '\\cos \\frac{7\\pi}{6}', correctAnswerId: 'ans11', category: 'H2' },
  { id: 'p76', question: '\\cos \\frac{5\\pi}{4}', correctAnswerId: 'ans10', category: 'H2' },
  { id: 'p77', question: '\\cos \\frac{4\\pi}{3}', correctAnswerId: 'ans9', category: 'H2' },
  { id: 'p78', question: '\\cos \\frac{3\\pi}{2}', correctAnswerId: 'ans1', category: 'H2' },
  { id: 'p79', question: '\\cos \\frac{5\\pi}{3}', correctAnswerId: 'ans2', category: 'H2' },
  { id: 'p80', question: '\\cos \\frac{7\\pi}{4}', correctAnswerId: 'ans3', category: 'H2' },
  { id: 'p81', question: '\\cos \\frac{11\\pi}{6}', correctAnswerId: 'ans4', category: 'H2' },
  { id: 'p82', question: '\\cos 2\\pi', correctAnswerId: 'ans7', category: 'H2' },
  { id: 'p83', question: '\\cos \\frac{13\\pi}{6}', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p84', question: '\\cos \\frac{9\\pi}{4}', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p85', question: '\\cos \\frac{7\\pi}{3}', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p86', question: '\\cos \\frac{5\\pi}{2}', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p87', question: '\\cos \\frac{8\\pi}{3}', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p88', question: '\\cos \\frac{11\\pi}{3}', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p89', question: '\\cos \\frac{17\\pi}{3}', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p90', question: '\\cos 3\\pi', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p91', question: '\\cos \\frac{19\\pi}{6}', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p92', question: '\\cos \\frac{13\\pi}{4}', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p93', question: '\\cos \\frac{10\\pi}{3}', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p94', question: '\\cos \\frac{21\\pi}{4}', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p95', question: '\\cos \\frac{22\\pi}{3}', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p96', question: '\\cos \\frac{27\\pi}{12}', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p97', question: '\\cos \\frac{23\\pi}{12}', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p98', question: '\\cos 4\\pi', correctAnswerId: 'ans7', category: 'H3' },

  { id: 'p99', question: '\\tan(-2\\pi)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p100', question: '\\tan(-\\frac{11\\pi}{6})', correctAnswerId: 'ans5', category: 'H0' },
  { id: 'p101', question: '\\tan(-\\frac{7\\pi}{4})', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p102', question: '\\tan(-\\frac{5\\pi}{3})', correctAnswerId: 'ans6', category: 'H0' },
  { id:103, question: '\\tan(-\\frac{3\\pi}{2})', correctAnswerId: 'ans8', category: 'H0' },
  { id: 'p104', question: '\\tan(-\\frac{4\\pi}{3})', correctAnswerId: 'ans13', category: 'H0' },
  { id: 'p105', question: '\\tan(-\\frac{5\\pi}{4})', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p106', question: '\\tan(-\\frac{7\\pi}{6})', correctAnswerId: 'ans12', category: 'H0' },
  { id: 'p107', question: '\\tan(-\\pi)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p108', question: '\\tan(-\\frac{5\\pi}{6})', correctAnswerId: 'ans5', category: 'H0' },
  { id: 'p109', question: '\\tan(-\\frac{3\\pi}{4})', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p110', question: '\\tan(-\\frac{2\\pi}{3})', correctAnswerId: 'ans6', category: 'H0' },
  { id: 'p111', question: '\\tan(-\\frac{\\pi}{2})', correctAnswerId: 'ans8', category: 'H0' },
  { id: 'p112', question: '\\tan(-\\frac{\\pi}{3})', correctAnswerId: 'ans13', category: 'H0' },
  { id: 'p113', question: '\\tan(-\\frac{\\pi}{4})', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p114', question: '\\tan(-\\frac{\\pi}{6})', correctAnswerId: 'ans12', category: 'H0' },
  { id: 'p115', question: '\\tan 0', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p116', question: '\\tan \\frac{\\pi}{6}', correctAnswerId: 'ans5', category: 'H1' },
  { id: 'p117', question: '\\tan \\frac{\\pi}{4}', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p118', question: '\\tan \\frac{\\pi}{3}', correctAnswerId: 'ans6', category: 'H1' },
  { id: 'p119', question: '\\tan \\frac{\\pi}{2}', correctAnswerId: 'ans8', category: 'H1' },
  { id: 'p120', question: '\\tan \\frac{2\\pi}{3}', correctAnswerId: 'ans13', category: 'H1' },
  { id: 'p121', question: '\\tan \\frac{3\\pi}{4}', correctAnswerId: 'ans14', category: 'H1' },
  { id: 'p122', question: '\\tan \\frac{5\\pi}{6}', correctAnswerId: 'ans12', category: 'H1' },
  { id: 'p123', question: '\\tan \\pi', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p124', question: '\\tan \\frac{7\\pi}{6}', correctAnswerId: 'ans5', category: 'H2' },
  { id: 'p125', question: '\\tan \\frac{5\\pi}{4}', correctAnswerId: 'ans7', category: 'H2' },
  { id: 'p126', question: '\\tan \\frac{4\\pi}{3}', correctAnswerId: 'ans6', category: 'H2' },
  { id: 'p127', question: '\\tan \\frac{3\\pi}{2}', correctAnswerId: 'ans8', category: 'H2' },
  { id: 'p128', question: '\\tan \\frac{5\\pi}{3}', correctAnswerId: 'ans13', category: 'H2' },
  { id: 'p129', question: '\\tan \\frac{7\\pi}{4}', correctAnswerId: 'ans14', category: 'H2' },
  { id: 'p130', question: '\\tan \\frac{11\\pi}{6}', correctAnswerId: 'ans12', category: 'H2' },
  { id: 'p131', question: '\\tan 2\\pi', correctAnswerId: 'ans1', category: 'H2' },
  { id: 'p132', question: '\\tan \\frac{13\\pi}{6}', correctAnswerId: 'ans5', category: 'H3' },
  { id: 'p133', question: '\\tan \\frac{9\\pi}{4}', correctAnswerId: 'ans7', category: 'H3' },
  { id: 'p134', question: '\\tan \\frac{7\\pi}{3}', correctAnswerId: 'ans6', category: 'H3' },
  { id: 'p135', question: '\\tan \\frac{5\\pi}{2}', correctAnswerId: 'ans8', category: 'H3' },
  { id: 'p136', question: '\\tan \\frac{8\\pi}{3}', correctAnswerId: 'ans13', category: 'H3' },
  { id: 'p137', question: '\\tan \\frac{11\\pi}{3}', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p138', question: '\\tan \\frac{17\\pi}{6}', correctAnswerId: 'ans12', category: 'H3' },
  { id: 'p139', question: '\\tan 3\\pi', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p140', question: '\\tan \\frac{19\\pi}{6}', correctAnswerId: 'ans5', category: 'H3' },
  { id: 'p141', question: '\\tan \\frac{13\\pi}{4}', correctAnswerId: 'ans7', category: 'H3' },
  { id: 'p142', question: '\\tan \\frac{10\\pi}{3}', correctAnswerId: 'ans6', category: 'H3' },
  { id: 'p143', question: '\\tan \\frac{21\\pi}{4}', correctAnswerId: 'ans8', category: 'H3' },
  { id: 'p144', question: '\\tan \\frac{22\\pi}{3}', correctAnswerId: 'ans13', category: 'H3' },
  { id: 'p145', question: '\\tan \\frac{27\\pi}{12}', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p146', question: '\\tan \\frac{23\\pi}{12}', correctAnswerId: 'ans12', category: 'H3' },
  { id: 'p147', question: '\\tan 4\\pi', correctAnswerId: 'ans1', category: 'H3' },
];