export const problemsDeg = [
  { id: 'p1', question: '\\sin(-360^\\circ)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p2', question: '\\sin(-330^\\circ)', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p3', question: '\\sin(-315^\\circ)', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p4', question: '\\sin(-300^\\circ)', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p5', question: '\\sin(-270^\\circ)', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p6', question: '\\sin(-240^\\circ)', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p7', question: '\\sin(-225^\\circ)', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p8', question: '\\sin(-210^\\circ)', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p9', question: '\\sin(-180^\\circ)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p10', question: '\\sin(-150^\\circ)', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p11', question: '\\sin(-135^\\circ)', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p12', question: '\\sin(-120^\\circ)', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p13', question: '\\sin(-90^\\circ)', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p14', question: '\\sin(-60^\\circ)', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p15', question: '\\sin(-45^\\circ)', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p16', question: '\\sin(-30^\\circ)', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p17', question: '\\sin 0^\\circ', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p18', question: '\\sin 30^\\circ', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p19', question: '\\sin 45^\\circ', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p20', question: '\\sin 60^\\circ', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p21', question: '\\sin 90^\\circ', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p22', question: '\\sin 120^\\circ', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p23', question: '\\sin 135^\\circ', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p24', question: '\\sin 150^\\circ', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p25', question: '\\sin 180^\\circ', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p26', question: '\\sin 210^\\circ', correctAnswerId: 'ans9', category: 'H2' },
  { id: 'p27', question: '\\sin 225^\\circ', correctAnswerId: 'ans10', category: 'H2' },
  { id: 'p28', question: '\\sin 240^\\circ', correctAnswerId: 'ans11', category: 'H2' },
  { id: 'p29', question: '\\sin 270^\\circ', correctAnswerId: 'ans14', category: 'H2' },
  { id: 'p30', question: '\\sin 300^\\circ', correctAnswerId: 'ans11', category: 'H2' },
  { id: 'p31', question: '\\sin 315^\\circ', correctAnswerId: 'ans10', category: 'H2' },
  { id: 'p32', question: '\\sin 330^\\circ', correctAnswerId: 'ans9', category: 'H2' },
  { id: 'p33', question: '\\sin 360^\\circ', correctAnswerId: 'ans1', category: 'H2' },
  { id: 'p34', question: '\\sin 390^\\circ', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p35', question: '\\sin 405^\\circ', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p36', question: '\\sin 420^\\circ', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p37', question: '\\sin 450^\\circ', correctAnswerId: 'ans7', category: 'H3' },
  { id: 'p38', question: '\\sin 480^\\circ', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p39', question: '\\sin 495^\\circ', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p40', question: '\\sin 510^\\circ', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p41', question: '\\sin 540^\\circ', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p42', question: '\\sin 570^\\circ', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p43', question: '\\sin 585^\\circ', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p44', question: '\\sin 600^\\circ', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p45', question: '\\sin 630^\\circ', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p46', question: '\\sin 660^\\circ', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p47', question: '\\sin 675^\\circ', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p48', question: '\\sin 690^\\circ', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p49', question: '\\sin 720^\\circ', correctAnswerId: 'ans1', category: 'H3' },

  { id: 'p50', question: '\\cos(-360^\\circ)', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p51', question: '\\cos(-330^\\circ)', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p52', question: '\\cos(-315^\\circ)', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p53', question: '\\cos(-300^\\circ)', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p54', question: '\\cos(-270^\\circ)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p55', question: '\\cos(-240^\\circ)', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p56', question: '\\cos(-225^\\circ)', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p57', question: '\\cos(-210^\\circ)', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p58', question: '\\cos(-180^\\circ)', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p59', question: '\\cos(-150^\\circ)', correctAnswerId: 'ans11', category: 'H0' },
  { id: 'p60', question: '\\cos(-135^\\circ)', correctAnswerId: 'ans10', category: 'H0' },
  { id: 'p61', question: '\\cos(-120^\\circ)', correctAnswerId: 'ans9', category: 'H0' },
  { id: 'p62', question: '\\cos(-90^\\circ)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p63', question: '\\cos(-60^\\circ)', correctAnswerId: 'ans2', category: 'H0' },
  { id: 'p64', question: '\\cos(-45^\\circ)', correctAnswerId: 'ans3', category: 'H0' },
  { id: 'p65', question: '\\cos(-30^\\circ)', correctAnswerId: 'ans4', category: 'H0' },
  { id: 'p66', question: '\\cos 0^\\circ', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p67', question: '\\cos 30^\\circ', correctAnswerId: 'ans4', category: 'H1' },
  { id: 'p68', question: '\\cos 45^\\circ', correctAnswerId: 'ans3', category: 'H1' },
  { id: 'p69', question: '\\cos 60^\\circ', correctAnswerId: 'ans2', category: 'H1' },
  { id: 'p70', question: '\\cos 90^\\circ', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p71', question: '\\cos 120^\\circ', correctAnswerId: 'ans9', category: 'H1' },
  { id: 'p72', question: '\\cos 135^\\circ', correctAnswerId: 'ans10', category: 'H1' },
  { id: 'p73', question: '\\cos 150^\\circ', correctAnswerId: 'ans11', category: 'H1' },
  { id: 'p74', question: '\\cos 180^\\circ', correctAnswerId: 'ans14', category: 'H1' },
  { id: 'p75', question: '\\cos 210^\\circ', correctAnswerId: 'ans11', category: 'H2' },
  { id: 'p76', question: '\\cos 225^\\circ', correctAnswerId: 'ans10', category: 'H2' },
  { id: 'p77', question: '\\cos 240^\\circ', correctAnswerId: 'ans9', category: 'H2' },
  { id: 'p78', question: '\\cos 270^\\circ', correctAnswerId: 'ans1', category: 'H2' },
  { id: 'p79', question: '\\cos 300^\\circ', correctAnswerId: 'ans2', category: 'H2' },
  { id: 'p80', question: '\\cos 315^\\circ', correctAnswerId: 'ans3', category: 'H2' },
  { id: 'p81', question: '\\cos 330^\\circ', correctAnswerId: 'ans4', category: 'H2' },
  { id: 'p82', question: '\\cos 360^\\circ', correctAnswerId: 'ans7', category: 'H2' },
  { id: 'p83', question: '\\cos 390^\\circ', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p84', question: '\\cos 405^\\circ', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p85', question: '\\cos 420^\\circ', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p86', question: '\\cos 450^\\circ', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p87', question: '\\cos 480^\\circ', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p88', question: '\\cos 495^\\circ', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p89', question: '\\cos 510^\\circ', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p90', question: '\\cos 540^\\circ', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p91', question: '\\cos 570^\\circ', correctAnswerId: 'ans11', category: 'H3' },
  { id: 'p92', question: '\\cos 585^\\circ', correctAnswerId: 'ans10', category: 'H3' },
  { id: 'p93', question: '\\cos 600^\\circ', correctAnswerId: 'ans9', category: 'H3' },
  { id: 'p94', question: '\\cos 630^\\circ', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p95', question: '\\cos 660^\\circ', correctAnswerId: 'ans2', category: 'H3' },
  { id: 'p96', question: '\\cos 675^\\circ', correctAnswerId: 'ans3', category: 'H3' },
  { id: 'p97', question: '\\cos 690^\\circ', correctAnswerId: 'ans4', category: 'H3' },
  { id: 'p98', question: '\\cos 720^\\circ', correctAnswerId: 'ans7', category: 'H3' },

  { id: 'p99', question: '\\tan(-360^\\circ)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p100', question: '\\tan(-330^\\circ)', correctAnswerId: 'ans5', category: 'H0' },
  { id: 'p101', question: '\\tan(-315^\\circ)', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p102', question: '\\tan(-300^\\circ)', correctAnswerId: 'ans6', category: 'H0' },
  { id: 'p103', question: '\\tan(-270^\\circ)', correctAnswerId: 'ans8', category: 'H0' },
  { id: 'p104', question: '\\tan(-240^\\circ)', correctAnswerId: 'ans13', category: 'H0' },
  { id: 'p105', question: '\\tan(-225^\\circ)', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p106', question: '\\tan(-210^\\circ)', correctAnswerId: 'ans12', category: 'H0' },
  { id: 'p107', question: '\\tan(-180^\\circ)', correctAnswerId: 'ans1', category: 'H0' },
  { id: 'p108', question: '\\tan(-150^\\circ)', correctAnswerId: 'ans5', category: 'H0' },
  { id: 'p109', question: '\\tan(-135^\\circ)', correctAnswerId: 'ans7', category: 'H0' },
  { id: 'p110', question: '\\tan(-120^\\circ)', correctAnswerId: 'ans6', category: 'H0' },
  { id: 'p111', question: '\\tan(-90^\\circ)', correctAnswerId: 'ans8', category: 'H0' },
  { id: 'p112', question: '\\tan(-60^\\circ)', correctAnswerId: 'ans13', category: 'H0' },
  { id: 'p113', question: '\\tan(-45^\\circ)', correctAnswerId: 'ans14', category: 'H0' },
  { id: 'p114', question: '\\tan(-30^\\circ)', correctAnswerId: 'ans12', category: 'H0' },
  { id: 'p115', question: '\\tan 0^\\circ', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p116', question: '\\tan 30^\\circ', correctAnswerId: 'ans5', category: 'H1' },
  { id: 'p117', question: '\\tan 45^\\circ', correctAnswerId: 'ans7', category: 'H1' },
  { id: 'p118', question: '\\tan 60^\\circ', correctAnswerId: 'ans6', category: 'H1' },
  { id: 'p119', question: '\\tan 90^\\circ', correctAnswerId: 'ans8', category: 'H1' },
  { id: 'p120', question: '\\tan 120^\\circ', correctAnswerId: 'ans13', category: 'H1' },
  { id: 'p121', question: '\\tan 135^\\circ', correctAnswerId: 'ans14', category: 'H1' },
  { id: 'p122', question: '\\tan 150^\\circ', correctAnswerId: 'ans12', category: 'H1' },
  { id: 'p123', question: '\\tan 180^\\circ', correctAnswerId: 'ans1', category: 'H1' },
  { id: 'p124', question: '\\tan 210^\\circ', correctAnswerId: 'ans5', category: 'H2' },
  { id: 'p125', question: '\\tan 225^\\circ', correctAnswerId: 'ans7', category: 'H2' },
  { id: 'p126', question: '\\tan 240^\\circ', correctAnswerId: 'ans6', category: 'H2' },
  { id: 'p127', question: '\\tan 270^\\circ', correctAnswerId: 'ans8', category: 'H2' },
  { id: 'p128', question: '\\tan 300^\\circ', correctAnswerId: 'ans13', category: 'H2' },
  { id: 'p129', question: '\\tan 315^\\circ', correctAnswerId: 'ans14', category: 'H2' },
  { id: 'p130', question: '\\tan 330^\\circ', correctAnswerId: 'ans12', category: 'H2' },
  { id: 'p131', question: '\\tan 360^\\circ', correctAnswerId: 'ans1', category: 'H2' },
  { id: 'p132', question: '\\tan 390^\\circ', correctAnswerId: 'ans5', category: 'H3' },
  { id: 'p133', question: '\\tan 405^\\circ', correctAnswerId: 'ans7', category: 'H3' },
  { id: 'p134', question: '\\tan 420^\\circ', correctAnswerId: 'ans6', category: 'H3' },
  { id: 'p135', question: '\\tan 450^\\circ', correctAnswerId: 'ans8', category: 'H3' },
  { id: 'p136', question: '\\tan 480^\\circ', correctAnswerId: 'ans13', category: 'H3' },
  { id: 'p137', question: '\\tan 495^\\circ', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p138', question: '\\tan 510^\\circ', correctAnswerId: 'ans12', category: 'H3' },
  { id: 'p139', question: '\\tan 540^\\circ', correctAnswerId: 'ans1', category: 'H3' },
  { id: 'p140', question: '\\tan 570^\\circ', correctAnswerId: 'ans5', category: 'H3' },
  { id: 'p141', question: '\\tan 585^\\circ', correctAnswerId: 'ans7', category: 'H3' },
  { id: 'p142', question: '\\tan 600^\\circ', correctAnswerId: 'ans6', category: 'H3' },
  { id: 'p143', question: '\\tan 630^\\circ', correctAnswerId: 'ans8', category: 'H3' },
  { id: 'p144', question: '\\tan 660^\\circ', correctAnswerId: 'ans13', category: 'H3' },
  { id: 'p145', question: '\\tan 675^\\circ', correctAnswerId: 'ans14', category: 'H3' },
  { id: 'p146', question: '\\tan 690^\\circ', correctAnswerId: 'ans12', category: 'H3' },
  { id: 'p147', question: '\\tan 720^\\circ', correctAnswerId: 'ans1', category: 'H3' },
];