import Cookie from "@/components/Background/Particles/Cookie";
import Header from "../../components/Header/Header";
import "./globals.css";
import Particles from "@/components/Background/Particles/Particles";

export const metadata = {
  title: "Math_App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <Header></Header>
        <Particles />
        <Cookie />
        {children}
      </body>
    </html>
  );
}