import Header from "../../components/Header/Header";
import AnimatedBackground from '@/components/AnimatedBackground/AnimatedBackground';
import "./globals.css";

export const metadata = {
  title: "Math_App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <Header></Header>
        <AnimatedBackground />
        {children}
      </body>
    </html>
  );
}
